# Generated by Django 5.2.7 on 2026-09-17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_billingeventlog_plan_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="credits",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
